"""
Snapshot data model for storing simulation state.

This module defines the data structure for saving and loading simulation snapshots.
Snapshots are generated by the solver and consumed by the trace viewer.
"""

from dataclasses import dataclass, field
from typing import Optional, Dict, Any
import numpy as np
import pickle


@dataclass
class Snapshot:
    """Simulation snapshot at a single timestep.
    
    Required fields for trace viewer functionality.
    Optional fields enhance the trace analysis capabilities.
    """
    # Required fields
    u: np.ndarray  # x-velocity field (Nx, Ny)
    v: np.ndarray  # y-velocity field (Nx, Ny)
    p: np.ndarray  # pressure field (Nx, Ny)
    mask: np.ndarray  # obstacle mask (Nx, Ny)
    dt: float  # timestep size
    nu: float  # kinematic viscosity
    dx: float  # grid spacing in x
    dy: float  # grid spacing in y
    
    # Optional fields
    divergence: Optional[np.ndarray] = None  # divergence field (Nx, Ny)
    Re: Optional[float] = None  # Reynolds number
    CFL: Optional[float] = None  # CFL number
    flow_type: Optional[str] = None  # flow configuration type
    solver_metadata: Optional[Dict[str, Any]] = None  # solver-specific metadata
    iteration: int = 0  # timestep index
    timestamp: Optional[float] = None  # simulation time
    
    def __post_init__(self):
        """Validate snapshot dimensions."""
        nx, ny = self.u.shape
        assert self.v.shape == (nx, ny), "v must have same shape as u"
        assert self.p.shape == (nx, ny), "p must have same shape as u"
        assert self.mask.shape == (nx, ny), "mask must have same shape as u"
        if self.divergence is not None:
            assert self.divergence.shape == (nx, ny), "divergence must have same shape as u"
    
    @property
    def shape(self) -> tuple:
        """Return grid shape (nx, ny)."""
        return self.u.shape
    
    @property
    def nx(self) -> int:
        """Return number of grid points in x."""
        return self.u.shape[0]
    
    @property
    def ny(self) -> int:
        """Return number of grid points in y."""
        return self.u.shape[1]
    
    def save(self, filepath: str) -> None:
        """Save snapshot to file."""
        with open(filepath, 'wb') as f:
            pickle.dump(self, f)
    
    @classmethod
    def load(cls, filepath: str) -> 'Snapshot':
        """Load snapshot from file."""
        with open(filepath, 'rb') as f:
            return pickle.load(f)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert snapshot to dictionary for serialization."""
        return {
            'u': self.u,
            'v': self.v,
            'p': self.p,
            'mask': self.mask,
            'dt': self.dt,
            'nu': self.nu,
            'dx': self.dx,
            'dy': self.dy,
            'divergence': self.divergence,
            'Re': self.Re,
            'CFL': self.CFL,
            'flow_type': self.flow_type,
            'solver_metadata': self.solver_metadata,
            'iteration': self.iteration,
            'timestamp': self.timestamp
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Snapshot':
        """Create snapshot from dictionary."""
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class SnapshotSeries:
    """Collection of snapshots representing a full simulation run."""
    snapshots: list[Snapshot] = field(default_factory=list)
    
    def add_snapshot(self, snapshot: Snapshot) -> None:
        """Add a snapshot to the series."""
        self.snapshots.append(snapshot)
    
    def __len__(self) -> int:
        """Return number of snapshots."""
        return len(self.snapshots)
    
    def __getitem__(self, index: int) -> Snapshot:
        """Get snapshot by index."""
        return self.snapshots[index]
    
    def save(self, filepath: str) -> None:
        """Save snapshot series to file."""
        with open(filepath, 'wb') as f:
            pickle.dump(self, f)
    
    @classmethod
    def load(cls, filepath: str) -> 'SnapshotSeries':
        """Load snapshot series from file."""
        with open(filepath, 'rb') as f:
            loaded_obj = pickle.load(f)
            
        # Handle both single Snapshot and SnapshotSeries objects
        if isinstance(loaded_obj, Snapshot):
            # Wrap single snapshot in a series
            return cls(snapshots=[loaded_obj])
        elif isinstance(loaded_obj, SnapshotSeries):
            return loaded_obj
        else:
            raise ValueError(f"Expected Snapshot or SnapshotSeries, got {type(loaded_obj)}")
