"""
State management module for the CFD viewer.
Provides Redux-style unidirectional data flow.
"""

from .store import (
    Store,
    Action,
    ActionType,
    AppState,
    ObstacleState,
    SimulationState,
    root_reducer,
    obstacle_reducer,
    simulation_reducer,
    store,
    logging_middleware,
    # Action creators
    set_obstacle_type,
    set_naca_airfoil,
    set_naca_chord,
    set_naca_angle,
    set_naca_x,
    set_naca_y,
    set_cylinder_radius,
    set_cylinder_center_x,
    set_cylinder_center_y,
    set_obstacle_position,
    set_reynolds_number,
    set_u_inf,
    set_nu,
    set_grid_nx,
    set_grid_ny,
)

__all__ = [
    'Store',
    'Action',
    'ActionType',
    'AppState',
    'ObstacleState',
    'SimulationState',
    'root_reducer',
    'obstacle_reducer',
    'simulation_reducer',
    'store',
    'logging_middleware',
    'set_obstacle_type',
    'set_naca_airfoil',
    'set_naca_chord',
    'set_naca_angle',
    'set_naca_x',
    'set_naca_y',
    'set_cylinder_radius',
    'set_cylinder_center_x',
    'set_cylinder_center_y',
    'set_obstacle_position',
    'set_reynolds_number',
    'set_u_inf',
    'set_nu',
    'set_grid_nx',
    'set_grid_ny',
]
